version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "PostgreSQL@2019"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fake@email.com"
      PGADMIN_DEFAULT_PASSWORD: "PostgreSQL@2019"
    ports:
      - "8081:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
