version: "3" 
services:

  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data:/var/lib/mysql"
      - "./mysql/initial_data:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456

volumes:
  db_data:
